### ISSUE TITLE
Support scala 2.12

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1414]
It is non-trivial to release a Scala 2.12 build of ENSIME because we depend on middleware that must also be available. This is a list of subtasks that are blocking the release:

**If you came here to check on the status of 2.12, but don't have time to dedicate to help us all achieve these goals, please consider [sponsorship](http://ensime.github.io/sponsor/)**

- [x] [java 8](https://github.com/ensime/ensime-server/pull/1639) not as trivial as you'd like to think... thanks Windows
- [x] akka - does not (and will not) have a cross build that works for both scala-2.10/scala-2.11/scala-2.12 at the same time.
- [ ] merge [the graphpocalypse](https://github.com/ensime/ensime-server/issues/1509) which removes a dependency on slick
- [x] scala-refactoring - is not necessarily available for new versions of scala. Ideally we'd make the refactoring logic optional on a per scala version basis (using the `BackCompat` pattern, maybe flag tests with tags).
- [x] scala-debugging - is closely tied to the binary format of scala. Ideally we'd make the debugging logic optional on a per scala version basis (using the `BackCompat` pattern, maybe flag tests with tags)..
- [x] spire / cats / macro-compat - are used in our tests and must be upgraded to a version that is cross build to 2.10/2.11/2.12, which will also involve updating the test assertions and perhaps addressing new bugs that arise
- [x] addressing general bugs that arise as a result of the binary format changes.
- [ ] scalamock could be removed and is only used in two places (although it will still be needed transitively by some of our dependencies).
- [x] we [don't need scalariform anymore](https://github.com/ensime/ensime-server/issues/1622) but it requires some work to reimplement one thing

We're waiting for a binary release of the following (links for non-trivial updates): 
- [x] [akka / testkit](https://github.com/akka/akka/issues/21763)
- [x] scalatest / scalactic
- [x] scalacheck
- [x] [scalamock](https://github.com/paulbutcher/ScalaMock/issues/119) @paulbutcher (unless removed)
- [x] shapeless
- [x] spray-json
- [x] parboiled2
- [x] spray-json-shapeless
- [x] [slick](https://github.com/slick/slick/issues/1572) (unless we remove)
- [x] [scala-refactoring](https://github.com/scala-ide/scala-refactoring/issues/168) @dragos / @sschaef  / @mlangc
- [x] [scalariform](https://github.com/scala-ide/scalariform/issues/232) @sschaef  / @SethTisue
- [x] [scala-debugging](https://github.com/ensime/scala-debugger/issues/72) @chipsenkbeil (unless optional)
- [x] scalatags / sourcecode @lihaoyi
- [x] spire / cats / macro-compat (we use these in the tests)

**Comment by chipsenkbeil** [comment]
The debugger api will need to do this as well down the road, I'm assuming.

**Comment by fommil** [comment]
once we release 1.0 it'll be a lot easier for us to be able to do matrix builds. We'll need to add `jenv` and openjdk8 to the `ensime/ensime:v2.x` docker image.

**Comment by jrudolph** [comment]
> akka-http @jrudolph (we're on version 1.0, any chance it'll be released? Do you know anyone who can help us migrate to the latest API?)

1.0? That's really old. I guess there might be a 2.0.4 for Scala 2.12 at some point but most likely you'll have to upgrade to 2.4.x (I can help with the migration if needed).

Btw. I created a release train for M4 again to make it easier to keep track of already released artifacts: https://blog.virtual-void.net/scala-infrastructure-tools/#releasetrainreportfor2120m4httpsgistgithubcomjrudolphd0e20c4a20af44459de1

**Comment by fommil** [comment]
@jrudolph that'd be great if you could help with the migration! We only use akka-http / stream in one package around here https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/WebServer.scala (and tests in the usual place). If anybody would like to help with this, please start here by upgrading us (might also requires changes to our use of akka elsewhere)

**Comment by fommil** [comment]
On gitter it would appear that the akka team are dead against publishing a version of akka 2.3 for scala 2.12. So it sounds like it's an all-or-nothing required upgrade to Java 8. We could try publishing our own versions of akka 2.3 as a stop gap.

**Comment by fommil** [comment]
I have other priorities, but this is about as far as I got with a 2.12 build of akka 2.3. It would require all the akka dependencies to be published for 2.12 as well (or akka upgraded to use them). I also got a few compile errors.

It looks pretty easy to do this, but the problem is that there doesn't appear to be a simple "sbt compile" command that one can type to build all of akka. Apparently removing streams might be sensible too as it is in a separate repo. It's all a bit of a mess to be honest. My motivation to do this is very low, I'd much rather put the effort into removing akka from our dependency list.

```diff
Head:     70f4538 Update version for release 2.3.15
Tag:      v2.3.15

Unstaged changes (2)
modified   project/AkkaBuild.scala
@@ -77,7 +77,7 @@ object AkkaBuild extends Build {
       validatePullRequest <<= (Unidoc.unidoc, SphinxSupport.generate in Sphinx in docs) map { (_, _) => }
     ),
     aggregate = Seq(actor, testkit, actorTests, dataflow, remote, remoteTests, camel, cluster, slf4j, agent, transactor,
-      persistence, persistenceTck, mailboxes, zeroMQ, kernel, osgi, docs, contrib, samples, multiNodeTestkit)
+      persistence, persistenceTck, mailboxes, kernel, osgi, docs, contrib, samples, multiNodeTestkit)
   )
 
   lazy val akkaScalaNightly = Project(
@@ -335,16 +335,6 @@ object AkkaBuild extends Build {
     )
   )
 
-  lazy val zeroMQ = Project(
-    id = "akka-zeromq",
-    base = file("akka-zeromq"),
-    dependencies = Seq(actor, testkit % "test;test->test"),
-    settings = defaultSettings ++ formatSettings ++ scaladocSettings ++ javadocSettings ++ OSGi.zeroMQ ++ Seq(
-      Dependencies.zeroMQ,
-      previousArtifact := akkaPreviousArtifact("akka-zeromq").value
-    )
-  )
-
   lazy val kernel = Project(
     id = "akka-kernel",
     base = file("akka-kernel"),
@@ -581,7 +571,7 @@ object AkkaBuild extends Build {
     id = "akka-docs",
     base = file("akka-docs"),
     dependencies = Seq(actor, testkit % "test->test",
-      remote % "compile;test->test", cluster, slf4j, agent, zeroMQ, camel, osgi, persistence, persistenceTck),
+      remote % "compile;test->test", cluster, slf4j, agent, camel, osgi, persistence, persistenceTck),
     settings = defaultSettings ++ docFormatSettings ++ site.settings ++ site.sphinxSupport() ++ site.publishSite ++ sphinxPreprocessing ++ cpsPlugin ++ Seq(
       sourceDirectory in Sphinx <<= baseDirectory / "rst",
       sphinxPackages in Sphinx <+= baseDirectory { _ / "_sphinx" / "pygments" },
@@ -1107,8 +1097,6 @@ object AkkaBuild extends Build {
 
     val testkit = exports(Seq("akka.testkit.*"))
 
-    val zeroMQ = exports(Seq("akka.zeromq.*"), imports = Seq(protobufImport()) )
-
     val osgiOptionalImports = Seq(
       // needed because testkit is normally not used in the application bundle,
       // but it should still be included as transitive dependency and used by BundleDelegatingClassLoader
@@ -1143,11 +1131,11 @@ object Dependencies {
   import DependencyHelpers.ScalaVersionDependentModuleID._
 
   object Versions {
-    val crossScala = Seq("2.10.4", "2.11.5")
+    val crossScala = Seq("2.12.0-M4")
     val scala = crossScala.head
     val scalaStmVersion  = System.getProperty("akka.build.scalaStmVersion", "0.7")
     val genJavaDocVersion = System.getProperty("akka.build.genJavaDocVersion", "0.9")
-    val scalaTestVersion = System.getProperty("akka.build.scalaTestVersion", "2.1.3")
+    val scalaTestVersion = System.getProperty("akka.build.scalaTestVersion", "3.0.0-M16-SNAP4")
     val scalaCheckVersion = System.getProperty("akka.build.scalaCheckVersion", "1.11.3")
     val scalaContinuationsVersion = System.getProperty("akka.build.scalaContinuationsVersion", "1.0.2")
   }
@@ -1170,11 +1158,7 @@ object Dependencies {
     val scalaStm      = "org.scala-stm"              %% "scala-stm"                    % scalaStmVersion // Modified BSD (Scala)
 
     val slf4jApi      = "org.slf4j"                   % "slf4j-api"                    % "1.7.5"       // MIT
-    val zeroMQClient = ScalaVersionDependentModuleID.fromPF {
-      case version if version.startsWith("2.10") => "org.zeromq"                % "zeromq-scala-binding_2.10" % "0.0.7"        // ApacheV2
-      case version if version.startsWith("2.11") => "org.spark-project.zeromq"  % "zeromq-scala-binding_2.11" % "0.0.7-spark"  // ApacheV2
-      case v => throw new RuntimeException("Scala version $v not supported for zeromq")
-    }
+
     // mirrored in OSGi sample
     val uncommonsMath = "org.uncommons.maths"         % "uncommons-maths"              % "1.2.2a" exclude("jfree", "jcommon") exclude("jfree", "jfreechart")      // ApacheV2
     // mirrored in OSGi sample
@@ -1277,8 +1261,6 @@ object Dependencies {
 
   val docs = deps(Test.scalatest, Test.junit, Test.junitIntf, Test.scalaXml)
 
-  val zeroMQ = deps(protobuf, zeroMQClient, Test.scalatest, Test.junit)
-
   val clusterSample = Seq(Test.scalatest, sigar)
 
   val contrib = Seq(Test.junitIntf, Test.commonsIo)
modified   project/scripts/release
@@ -170,7 +170,7 @@ fi
 declare -r version=$1
 declare -r publish_path="${release_server}:${release_path}"
 
-[[ `java -version 2>&1 | grep "java version" | cut -d ' ' -f3 | cut -d '.' -f2` -eq 6 ]] || fail "Java version is not 1.6"
+[[ `java -version 2>&1 | grep "java version" | cut -d ' ' -f3 | cut -d '.' -f2` -eq 8 ]] || fail "Java version is not 1.8"
 
 # check for a git command
 type -P git &> /dev/null || fail "git command not found"

```

**Comment by jrudolph** [comment]
How long are you going to keep Java 6 compatibility? It will get harder and harder to find recent versions of any library that will still work with Java 6.

For the time being there are certainly stop gap solutions that should work well enough. The previously mentioned switch in your build between a 2.3.x Akka version for 2.11 / Java 6 and a 2.4.x Akka version for 2.12 / Java 8 should certainly be doable (would probably need some compat code because akka-http didn't stay exactly source compatible between the versions). I think this would still be fine for the short-term because in the middle-term when you drop Java 6 compatibility you could just throw away the Akka 2.3.x pieces.

If you want to support Java 6 for a longer time, then, yes, maybe Akka(-Http) is not the right way to go. For a project that just came out of experimental status like Akka-Http it makes sense to start from a clean slate and to avoid pre-Java-8 baggage (there are some subtle network and TLS related changes in recent JDKs whose alternatives would have had to be maintained otherwise). In fact, I'd even say that it would be negligent for a networking library to support old JDKs for which security updates are not expected any more. (In case, it's not clear I'm not speaking for the Akka team)

**Comment by fommil** [comment]
@jrudolph JDK6 is still the official JDK used by Scala 2.10 and 2.11, and one must use it to be part of the Community Build. We're going to break away and move to JDK7 after we release ENSIME 1.0. The vast majority of contributors are still using JDK7 in their day job and there are benefits for us to use JDK7 for NIO.

BTW, Oracle still makes security updates for JDK6 and JDK7, they are just not available as free-of-charge downloads and I am not aware of the source code being released by into OpenJDK.

I would actually like to remove Akka in general. I only ever used akka because I liked Spray. But ENSIME has only an incredibly small HTTP component that could easily be replaced with a Java library (or http4s). I really hate the Akka implementation of Actors, in every project where I've used it, I've regretted it because it throws away type safety and obfuscates all errors into incomprehensible stack traces. I just don't have the time to do the move right now, nor have I done the architecture work to conclude what the best alternative would be for us. There is a strong argument that we don't need anything of the sort and good old-fashioned service beans are all we need.

**Comment by fommil** [comment]
ok, looks like this is going to need a separate branch just for scala 2.12 since akka needs to be upgraded.

**Comment by fommil** [comment]
This simply isn't going to happen until we can remove our akka dependency.

**Comment by fommil** [comment]
@ktonga that's to unblocking akka-streams, we're now looking more likely to be able to make a 2.12-RC release at some point!

**Comment by ktonga** [comment]
No worries @fommil, I feel I owe it to the universe for starting so many projects in my akka-solves-all-the-problems days.

**Comment by kolektiv** [comment]
Is there any movement on this? Should I be tracking 2.0 if that's where it's likely to appear first? (This question asked solely in the spirit of interest, and with no accusation intended whatsoever - I know as well as anyone the challenges of getting stuff out with a lack of time/money/etc.)

**Comment by chipsenkbeil** [comment]
@kolektiv, slow progress. ScalaMock just got a 2.12 release, which enabled the Scala Debugger project to add a 2.12 build that just got released yesterday (along with several other improvements): https://github.com/ensime/scala-debugger/releases/tag/v1.1.0-M3

**Comment by kolektiv** [comment]
@chipsenkbeil good to know anyway. It's a complex project, always going to be tough. Thanks for the info, i'll keep an eye, and if I ever discover a way to help i will.

**Comment by chipsenkbeil** [comment]
@kolektiv, it's definitely coming along. :) I think akka is supposed to be the most troublesome, but @fommil would know more about the current state.

**Comment by fommil** [comment]
Seems we're blocked by graphpocalypse and scala-refactoring at this point.

**Comment by chipsenkbeil** [comment]
@fommil, is akka done? There wasn't a checkmark by it's name, so I assumed it was still a todo.

**Comment by fommil** [comment]
I'm being lazy

**Comment by jvican** [comment]
Akka testkit for 2.12 [has been released](http://search.maven.org/#search|ga|1|a:"akka-testkit_2.12").
Scalamock [has also been released for 2.12](http://search.maven.org/#search|ga|1|a:"scalamock_2.12").
There seems to be also a 2.12 compatible version for Slick (only [3.2.0-M2](http://search.maven.org/#search|ga|1|a:"slick_2.12"), though).
  
I ticked the boxes of scalamock and testkit, please undo if I made a mistake.

**Comment by timcharper** [comment]
Looks like slick release is pending.

https://github.com/slick/slick/commit/f83fb1c02fa2a1f843b96dd6414ef6522c447f60

**Comment by fommil** [comment]
quick update for people, because this ticket has gone stale in preference of discussion on the PR, we are blocked on fixing bugs in scala-debugger and scala-refactoring

**Comment by chipsenkbeil** [comment]
@fommil, that's news to  me. What bugs in Scala debugger are blocking you?

**Comment by sugakandrey** [comment]
@fommil If you are talking about my PR, that assertion failure in `DebugTest` was actually just a design change in new `scala-debugger` version, not a bug.

**Comment by fommil** [comment]
ah! How dare I say there was a bug in the most epically tested lib in the scala ecosystem :stuck_out_tongue_winking_eye:

**Comment by alex3kov** [comment]
> fommil closed this 3 hours ago

Can you give us a quick tip of what to expect? Will 2.12 support be included in ensime 1.12.16, or 2.0.0 stable, or what?

**Comment by fommil** [comment]
what is ensime 1.12.16?

**Comment by fommil** [comment]
oh, you mean sbt-ensime. That's not how it works... the sbt plugin and server are independent. This support is in the 2.0.0-SNAPSHOT (developer version) and already supported in the sbt plugin. 2.0.0 will be released when all the tickets on the milestone are closed.

**Comment by alex3kov** [comment]
Right, sorry, I got server/sbt plugin mixed up :) Which **ensime-server** stable version will support scala 2.12?

**Comment by fommil** [comment]
Check the milestone ;-)

**Comment by macalinao** [comment]
woohoo!!!
